### ISSUE TITLE
easyplayer rtmp启动时异常，报错。不能正常运行

### ISSUE THREAD

**Issue by leebaozhong** [tsingsee/EasyPlayer-RTMP-Android#12]
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.bugly.beta.utils.BuglyFileProvider" on path: DexPathList[[zip file "/data/app/org.easydarwin.easyplayer.rtmp-NgkEX3fCjpEZPY3AUil4IQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.easydarwin.easyplayer.rtmp-NgkEX3fCjpEZPY3AUil4IQ==/lib/arm, /data/app/org.easydarwin.easyplayer.rtmp-NgkEX3fCjpEZPY3AUil4IQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at android.app.ActivityThread.installProvider(ActivityThread.java:8157)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7709) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573) 
        at android.app.ActivityThread.access$2600(ActivityThread.java:260) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8668) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 13 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/data/app/org.easydarwin.easyplayer.rtmp-NgkEX3fCjpEZPY3AUil4IQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.easydarwin.easyplayer.rtmp-NgkEX3fCjpEZPY3AUil4IQ==/lib/arm, /data/app/org.easydarwin.easyplayer.rtmp-NgkEX3fCjpEZPY3AUil4IQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)

**Comment by leo-09** [comment]
加QQ2779005381,获取技术支持
